services:
  portainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portainer
    image: portainer:latest
    restart: unless-stopped
    ports:
      - "9000:9000" # Web UI Port
      - "8000:8000" # Edge Agent Port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - nginxproxymanager_default
    environment:
      - TZ=UTC

volumes:
  portainer_data:

networks:
  nginxproxymanager_default:
    external: true
