services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-git
      - CUSTOM_USER=admin # Add a username
      - PASSWORD=yourpassword # Add a password
    volumes:
      - ./config:/config
      - /home/omoinjm/dev/github/docs/:/var/lib/obsidian/vaults
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
