services:
  nginx-proxy-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy-manager
    image: nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web UI Port
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm-net
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      # Postgres parameters:
      DB_POSTGRES_HOST: "db"
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_USER: "npm"
      DB_POSTGRES_PASSWORD: "npmpass"
      DB_POSTGRES_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "npm"
      POSTGRES_PASSWORD: "npmpass"
      POSTGRES_DB: "npm"
    volumes:
      - ./postgresql:/var/lib/postgresql

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  npm-net:
    name: npm-net
    driver: bridge
